<?php
/**
 * Created by PhpStorm.
 * User: webndesign
 * Date: 15.04.20
 * Time: 23:15
 */

namespace frontend\widgets\grid;

use yii\grid\DataColumn;
use yii\grid\GridView;
use yii\helpers\VarDumper;

class MetersDataGridView extends GridView
{

   protected function initColumns()
   {
       parent::initColumns(); // TODO: Change the autogenerated stub


       foreach ($this->columns as $i => $column) {

           if ($column instanceof DataColumn) {

                //VarDumper::dump($column->attribute, 20, true);
               if ($column->attribute === 'wmcold3') {
//                   if ($column->value === 0) {
//                       unset($this->columns[$i]);
//                       continue;
//                   }

               }
           }


       }


   }






}